# Generated by Django 3.2 on 2021-04-20 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='next_post',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='previous_post',
        ),
    ]
