# Generated by Django 3.2 on 2021-04-23 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_auto_20210420_1104'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category_name',
            old_name='category_name',
            new_name='name',
        ),
    ]
